Question 1

In [1]:
import pandas as pd


In [2]:
pd.__version__

'3.0.6'

In [8]:
import pandas as pd


In [10]:
df=pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [11]:
df.describe

<bound method NDFrame.describe of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4   
1           2008  Europe    Diesel  Front-wheel drive          4   
2           1996    Asia  Gasoline  Front-wheel drive          5   
3           1989  Europe  Gasoline  Front-wheel drive          4   
4           1994     USA    Diesel  Front-wheel drive          3   
...          ...     ...       ...                ...        ...   
9995        2005     USA  Gasoline    All-wheel drive          4   
9996        1993    Asia  Gasoline    All-wheel drive          2   
9997        2014     USA  Gasoline    All-wheel drive          3   
9998        2004     USA    Hybrid   Rear-wheel drive          5   
9999        2011     USA    Diesel  Front-wheel drive          4   

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870   
1    

Question 2

In [13]:
row_count=len(df)
row_count

10000

Question 3

In [15]:
df.fuel_type.nunique()

3

Question 4

In [16]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Question 5

In [19]:
max_fuel_eff =df.fuel_efficiency_mpg.max()
max_fuel_eff

np.float64(41.2)

Question 6

In [20]:
hpmedian=df.horsepower.median()
hpmedian

np.float64(254.0)

In [21]:
most_freq_hp=df['horsepower'].mode()[0]
most_freq_hp

np.float64(252.0)

In [23]:
df['horsepower'] = df['horsepower'].fillna(most_freq_hp)
hpmedian_2=df.horsepower.median()
hpmedian_2


np.float64(252.0)

In [26]:
hpmedians=[hpmedian,hpmedian_2]
hpmedians


[np.float64(254.0), np.float64(252.0)]

Question 7

In [27]:
import numpy as np

In [30]:
asia_cars = df[df['origin'] =='Asia']
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4


In [31]:
selected_cols = asia_cars[["vehicle_weight", "model_year"]]
first_7 = selected_cols.head(7)
first_7

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [32]:
X = first_7.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [33]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [34]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y
total_sum = np.sum(w)
total_sum

np.float64(0.36919696904925486)